### ISSUE TITLE
`make build` fails

### ISSUE THREAD

**Issue by trunc8** [sea-bass/turtlebot3_behavior_demos#1]
Hi, the error message is as follows:
```
Sending build context to Docker daemon  2.907MB
Step 1/15 : FROM nvidia_ros:latest
pull access denied for nvidia_ros, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:48: build-base] Error 1
```

Is nvidia_ros not a standard DockerHub image? It would be great if you could prepend those steps in the instructions.
Kudos to the corresponding blog post though! I learnt a lot from that

**Comment by sea-bass** [comment]
Thank you!

Actually, `nvidia-ros` is not a standard DockerHub image, but there already was a `build-core` target to build this... I just forgot to add the dependency.  Try pulling again and see if it works?

```
# Build the core image
.PHONY: build-core
build-core:
	@docker build -f ${CORE_DOCKERFILE} -t nvidia_ros .

# Build the base image
.PHONY: build-base
build-base: build-core
	@docker build -f ${BASE_DOCKERFILE} -t ${IMAGE_NAME}_base .

# Build the overlay image (depends on base image build)
.PHONY: build
build: build-base
	@docker build -f ${OVERLAY_DOCKERFILE} -t ${IMAGE_NAME}_overlay .
```

**Comment by trunc8** [comment]
Thanks, `make build` works now
