### ISSUE TITLE
`make build` fails

### ISSUE THREAD

**Issue by PatJRobinson** [sea-bass/turtlebot3_behavior_demos#10]
Following the instructions, when I run `sudo make build`, I am greeted by the error  `unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /docker: no such file or directory`.

I fixed this by removing ${PWD} from the docker file paths in the MakeFile, however I am curious to know the cause of this issue, when no one else seems to have encountered it. Forgive my noobiness if it is obvious.

**Comment by sea-bass** [comment]
Do you happen to be on Windows, by any chance? Might be the case that the `$PWD` env variable isn't friendly to that, and should just be replaced by `.`.

Let me know!

Either way, now that I know better, I really need to update this example to use Docker compose instead of make...

**Comment by sea-bass** [comment]
Closing this one and will keep working on the Humble transition since Groot seems to be broken on Galactic and that's about to go end of life in Nov 2022.
