### ISSUE TITLE
Help -- Local Setup

### ISSUE THREAD

**Issue by antbono** [sea-bass/turtlebot3_behavior_demos#29]
Hi everyone!

I am trying to run the demo based on the cpp library on my machine but I am missing something. I am running ros humble on ubu 22.04.

hereafter the steps I did:

1. I installed and tested the turtlebot package as suggested in the instructions.
2. I followed the instructions to build this demo in a local machine.
3. I downloaded the Groot2 app image, placed in the home folder, renamed it as `Groot2.AppImage ` (the file you download is slightly different) and I gave it execution permission.
4. In a shell I set `TURTLEBOT3_MODEL=waffle_pi` and launched `tb3_demo_world.launch.py`
5. In a shell I launched `tb3_demo_beahvior_cpp.launch.py`
6. In rviz I set manually the initial 2d pose estimation.

The following snapshots show what I got

![Screenshot from 2023-04-19 21-52-32](https://user-images.githubusercontent.com/7023471/233187989-b37f3178-b179-4491-992d-b8aa9f6f5b28.png)
![Screenshot from 2023-04-19 21-52-54](https://user-images.githubusercontent.com/7023471/233187996-45291826-8c62-4621-89bb-c9bcf4941a99.png)
![Screenshot from 2023-04-19 21-53-26](https://user-images.githubusercontent.com/7023471/233187997-e6b16898-cac3-4fc7-acd4-c97fb6f08da4.png)

I can't understand what I am missing to place the three objects and start the behavior.

Thank you very much fort your time and consideration!

**Comment by sea-bass** [comment]
The block spawner node probably died with some error ... If you scroll up on the output of `tb3_demo_world.launch.py`, are there any errors?

**Comment by antbono** [comment]
Yes there are some errors. I took a snapshot

![Screenshot from 2023-04-19 22-12-22](https://user-images.githubusercontent.com/7023471/233189176-60e263bc-925e-4e32-ad37-5cc38ab9b853.png)

**Comment by sea-bass** [comment]
Ah, can you do `pip3 install transforms3d` and try again?

Also highly recommend switching from Fast DDS to Cyclone DDS: https://docs.ros.org/en/humble/Installation/DDS-Implementations/Working-with-Eclipse-CycloneDDS.html -- this will get rid of a lot of the other spam and make things a bit more reliable

**Comment by antbono** [comment]
Thank you @sea-bass!

Now I can see all the objects and also rviz set automatically the initial pose estimation.

![Screenshot from 2023-04-19 22-28-14](https://user-images.githubusercontent.com/7023471/233192639-930ddec2-1a46-4f29-a2ef-7e823ab3a406.png)

What should I do to start the behavior?

**Comment by antbono** [comment]
I am sorry, I have been launching the behavior launch file before than the world launch file.
Now it seems to work fine. 

Should I do something with this error about openSSL?

![Screenshot from 2023-04-19 22-39-33](https://user-images.githubusercontent.com/7023471/233195526-0f0d83c1-e1e2-4d37-8680-38c9dd550d7e.png)

**Comment by sea-bass** [comment]
Great to hear! I should add some of these to the local setup steps.

I think the Groot2 SSL warnings are non critical, but perhaps there is something to remove the warnings?

**Comment by sea-bass** [comment]
@antbono You actually may be able to resolve the warnings with:

```
sudo apt-get install libssl1.1
```

Anyways, I updated the docs with some of the steps discussed in this issue. Thanks for reporting them!

**Comment by antbono** [comment]
@sea-bass Thank you for your super quick support! :D
