### ISSUE TITLE
Container has created but it shown Container is not running when exec 

### ISSUE THREAD

**Issue by Guo-oncloud** [sea-bass/turtlebot3_behavior_demos#38]
![image](https://github.com/sea-bass/turtlebot3_behavior_demos/assets/128336473/0fb497f3-7575-4519-81bb-0247ae085fa4)

**Comment by sea-bass** [comment]
That `docker ps` output says that container was exited 15 minutes ago, so seems to make sense.

Could you run `docker compose up <service name>` before trying again?

BTW a way to make this a little easier to type would be:

```
docker compose up <service>
docker compose exec -it <service> bash
```

**Comment by Guo-oncloud** [comment]
It looks like I just started the Docker, and the Docker will automatically exit
![image](https://github.com/sea-bass/turtlebot3_behavior_demos/assets/128336473/f29ec10b-6737-49ea-9dc4-542e18527975)
d the Docker, and the Docker will automatically exit，

**Comment by Guo-oncloud** [comment]
It looks like I just started the Docker, and the Docker will automatically exit
![image](https://github.com/sea-bass/turtlebot3_behavior_demos/assets/128336473/620f1a5c-3efd-4633-b3ab-514ef5135179)

**Comment by sea-bass** [comment]
Ah yes, looking at the docker compose file, it seems like starting up `base` or `overlay` won't work like that because they don't have any commands that keep them alive.

You can either do:

```
# Runs a bash instance in the "overlay" service
docker compose run overlay bash
```

or 

```
# Brings up an instance of the "dev" service (which has a "sleep infinity" command), which you can then attach to
docker compose up dev
docker compose exec -it dev bash
```

**Comment by Guo-oncloud** [comment]
Thanks
I have completed the previous steps and displayed python3 is not responding when `docker compose up demo-behavior-py`
![image](https://github.com/sea-bass/turtlebot3_behavior_demos/assets/128336473/f76a6017-c841-4863-8f05-19341e8e7f5e)
