### ISSUE TITLE
What is the publisher port in Groot?

### ISSUE THREAD

**Issue by MortezaAliyari** [sea-bass/turtlebot3_behavior_demos#4]
Hi, 
I followed the tutorial. I didn't use docker.I run `roslaunch tb3_worlds tb3_demo_world.launch ` without problem.
 After running the `roslaunch tb3_autonomy tb3_demo_behavior_cpp.launch ` the Groot editor opens but I'm not able to make a connection between ROS and Groot. 
it seems I need a publisher port number. the default is not working.
I'm using Ubuntu focal, ros noetic.
thanks for your support.

**Comment by sea-bass** [comment]
This is functionality in the [BehaviorTree.CPP](https://github.com/BehaviorTree/BehaviorTree.CPP) repo, so you may be better off asking there after providing any more detailed steps and/or error messages?

The constructor for `BT::PublisherZMQ` allows you to pass in a non-default (1666) publisher port number as shown [at this link in the code](https://github.com/BehaviorTree/BehaviorTree.CPP/blob/8db5593a880c60211a8871bfe4da5b2507f726b3/include/behaviortree_cpp_v3/loggers/bt_zmq_publisher.h#L16). Is this what you're changing when you say you "need a publisher port number"? And does the connection establish that way?

Could it be that when running locally there are some processes lingering between runs that are holding on to that port?
