### ISSUE TITLE
Why not use the Nav2 framework?

### ISSUE THREAD

**Issue by jwdinius** [sea-bass/turtlebot3_behavior_demos#46]
It looks like you've implemented behavior trees as your main goal manager, which is remarkably similar conceptually to what [Nav2](https://navigation.ros.org/concepts/index.html#behavior-trees) does (as your blog post mentions).  Why did you set up your simulation using BTs natively instead of integrating directly with the Nav2 framework?  Is there a particular feature lacking in Nav2 that you needed for your demonstration?

**Comment by sea-bass** [comment]
No, Nav2 is almost surely better featured than this. This is an educational repo meant to focus on writing BT code for some black box action (in this case, it's navigation hence the overlap). And of course, it has both C++ and Python examples which is a bit different from Nav2.

**Comment by jwdinius** [comment]
Perfect.  Thanks for the explanation.
