### ISSUE TITLE
Groot2 curl link not valid

### ISSUE THREAD

**Issue by AnsgarKasselmann** [sea-bass/turtlebot3_behavior_demos#47]
The curl link to Groot2 seems to be outdated. I'm getting the following response instead of the actual app image:

``` xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>F57GABXWYMH91Y8Q</RequestId>
  <HostId>L0+37M9FRcBsFLlaX6rACPdnFMnzAk933lMTJ4A9veWgoMlUahTeoFpLwoBycgEdvXkfu4ov3Ug=</HostId>
</Error>
```

**Comment by sea-bass** [comment]
Thanks for pointing this out.

Going on the [Groot web page](https://www.behaviortree.dev/groot/), it seems this is the latest link: https://s3.us-west-1.amazonaws.com/download.behaviortree.dev/groot2_linux_installer/Groot2-v1.5.2-x86_64.AppImage

Could you confirm whether this works?

**Comment by sea-bass** [comment]
I checked it myself and fixed in https://github.com/sea-bass/turtlebot3_behavior_demos/pull/48 -- thanks again for pointing out the dead link!
