### ISSUE TITLE
KeyError: 'location_file'

### ISSUE THREAD

**Issue by RicoJia** [sea-bass/turtlebot3_behavior_demos#5]
Hi, 
When I run `make demo-behavior`, I see `KeyError: 'location_file'`. 
In `autonomy_node.py`, looks like we are loading `"location_file"` ros parameter. However, I see that it's only being loaded in `tb3_world.launch`. I think that's probably reason why

**Comment by sea-bass** [comment]
Good catch! This caused an error in `make demo-behavior-cpp` as well for the exact same reason.

I added a wait to both nodes so you can actually start the behavior launch files before the world and the nodes will just wait for the world to start up.

Thanks!
